### PR TITLE
Removed functionality that requires fcntl for Windows usage

### PR DESCRIPTION
**Pull request by JakeCowton**
- All functionality that required `fcntl` has been removed to allow
  for compatability with windows

### CODE REVIEW

**Comment by skorokithakis** [comment]
Why remove this? Did it break the whole library in Windows?

**Comment by JakeCowton** [comment]
Yes. By removing all fcntl calls it works on windows.
Some more info on why this is the case [here](https://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows).
I'm not necessarily saying this should be merged, but it's the quick and dirty way to get this working in windows, though it does mean losing the `discover_bulbs()`functionality.

**Comment by skorokithakis** [comment]
But I don't understand, why not just avoid calling `discover_bulbs()` on Windows?

**Comment by JakeCowton** [comment]
When you run it, `import fcntl` is called, meaning it needs to be installed which is not possible on a Windows system.

**Comment by skorokithakis** [comment]
This has been fixed for a while, though, the library imports `win32api` on Windows:

https://github.com/skorokithakis/python-yeelight/blob/master/yeelight/main.py#L16

Which version were you using? I don't know why the diff here doesn't show that...

**Comment by skorokithakis** [comment]
Yeah, this PR is against a very old version. Can you try the latest one and let me know if it works?

**Pull request closed without merging**
