### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by filozof71**
set additional socked options to properly call multicast

### CODE REVIEW

**Comment by filozof71** [comment]
Hello. This is my first experience with github and python. I provided additional options to call multicast discover_bulbs function. In my experience your origonal code returns null []. After this chnge I am able to properly discover my RGB Bulb.

**Comment by skorokithakis** [comment]
Thank you!

**Comment by mariusrugan** [comment]
Hi

i'm using homeassistant / yeelight together with Mi LED Desk Lamp /aka/ Yeelight Desk Lamp; https://www.yeelight.com/en_US/product/mijia-lamp which lately got developer mode support with the latest firmware update. 
As HA uses yeelight package (stable release 0.3.2) in the yeelight component/platform imho would be more easy to extend it to properly handle the desklamp (right now BulbType.Unknown) which i'm prepared to do. 
Also, although the code below executes successfully (command is send over wire) exceptions occur. 

For some reason i don't see issues here in this project so  sorry for spitting the out the issue here, seems the most up-2-date place where @skorokithakis would look.
looking forward for your comments / suggestions

```
Python 3.4.2 (default, Oct  8 2014, 10:45:20)
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from yeelight import Bulb
>>> bulb = Bulb("X.Y")
>>> bulb.turn_on()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-7>", line 2, in turn_on
  File "/srv/homeassistant/lib/python3.4/site-packages/yeelight/main.py", line 53, in _command
    result = self.send_command(method, params).get("result", [])
  File "/srv/homeassistant/lib/python3.4/site-packages/yeelight/main.py", line 315, in send_command
    raise BulbException(response["error"])
yeelight.main.BulbException: Bulb closed the connection.
```

thanks for the patch @filozof71 / much more speedy now in discovery connections.

**Comment by skorokithakis** [comment]
Please file issues here: https://gitlab.com/stavros/python-yeelight/issues

**Pull request merged**
